import {useState} from 'react';
import {Link} from 'react-router-dom';
import {Plus,ArrowUpRight,GitBranch,RefreshCw,Box,Search} from 'lucide-react';
import {PageTitle,Panel,ProjectIcon,Status,Empty,ErrorNotice} from '../components/ui';
import {useAction,type Dashboard} from '../api';
export default function Projects({data,onNew}:{data:Dashboard;onNew:()=>void}){
 const [tab,setTab]=useState('Projects');const [filter,setFilter]=useState('all');const [query,setQuery]=useState('');const action=useAction();
 const projects=data.project.filter(p=>(filter==='all'||p.status===filter)&&`${p.name} ${p.stack}`.toLowerCase().includes(query.toLowerCase()));
 const repos=data.repository.filter(r=>(filter==='all'||r.state===filter)&&r.name.toLowerCase().includes(query.toLowerCase()));
 return <><PageTitle title="Projects" description="Everything you build, all in one place." action={<button className="button primary" onClick={onNew}><Plus size={16}/>New project</button>}/><div className="tabs">{['Projects','Repository discovery'].map(t=><button className={tab===t?'active':''} key={t} onClick={()=>{setTab(t);setFilter('all')}}>{t}<span>{t==='Projects'?data.project.length:data.repository.length}</span></button>)}</div><div className="toolbar"><div className="search-field"><Search size={16}/><input aria-label="Search projects or repositories" placeholder={tab==='Projects'?'Find a project…':'Find a repository…'} value={query} onChange={e=>setQuery(e.target.value)}/></div><select aria-label="Filter status" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All {tab==='Projects'?'statuses':'repositories'}</option>{(tab==='Projects'?['healthy','degraded','down','unknown']:['managed','unreviewed','ignored']).map(s=><option key={s}>{s}</option>)}</select>{tab!=='Projects'&&<button className="button" disabled={action.isPending} onClick={()=>action.mutate({path:'/repositories/discover'})}><RefreshCw size={15} className={action.isPending?'spin':''}/>Discover repositories</button>}</div><ErrorNotice error={action.error}/>{tab==='Projects'?<div className="project-grid">{projects.map(p=><Link className="project-card panel" to={'/projects/'+p.id} key={p.id}><div className="row between"><ProjectIcon project={p}/><ArrowUpRight size={17}/></div><h2>{p.name}</h2><p>{p.description}</p><div className="row gap"><span className="stack-label">{p.stack}</span><span className="muted">{p.provider}</span></div><div className="project-card-footer"><Status value={p.status}/><span><GitBranch size={13}/>{p.branch}</span></div></Link>)}<button className="project-card add-project" onClick={onNew}><div><Plus size={26}/><h3>Make room for your next idea</h3><p>Add a project to your control plane</p></div></button></div>:<Panel><div className="table-scroll"><table><thead><tr><th>Repository</th><th>Stack</th><th>State</th><th>Manage</th></tr></thead><tbody>{repos.map(r=><tr key={r.id}><td><div className="row gap"><Box size={17}/><b>{r.name}</b></div><small>{r.archived?'Archived · ':''}{r.fork?'Fork · ':''}{r.branch}</small></td><td>{r.stack}</td><td><Status value={r.state}/></td><td><select aria-label={`State of ${r.name}`} value={r.state} onChange={e=>action.mutate({path:'/repositories/state',method:'PATCH',body:{id:r.id,state:e.target.value}})}>{['unreviewed','managed','ignored'].map(s=><option key={s}>{s}</option>)}</select></td></tr>)}</tbody></table></div>{!repos.length&&<Empty title="No matching repositories" text="Discover repositories or adjust the filter. Ignored repositories are always recoverable."/>}</Panel>}</>
}
