import {useState} from 'react';
import {useParams,Link} from 'react-router-dom';
import {useQuery} from '@tanstack/react-query';
import {ArrowLeft,Rocket,RotateCcw,GitBranch,ShieldCheck,Activity,Check,KeyRound,Trash2} from 'lucide-react';
import {Panel,Status,ProjectIcon,External,ErrorNotice,Submit,Empty} from '../components/ui';
import {Security,Health,LogView} from './Operations';
import DeploymentsTable from '../components/DeploymentsTable';
import {api,useAction,ago,type Dashboard,type Item} from '../api';
export default function ProjectDetail({data,onSelect,onDeploy}:{data:Dashboard;onSelect:(d:Item)=>void;onDeploy:(p:Item,action?:string,target?:string)=>void}){
 const {id}=useParams();const [tab,setTab]=useState('Overview');const p=data.project.find(p=>p.id===id);const deps=data.deployment.filter(d=>d.project===id);const latest=deps[0];
 if(!p)return <Empty title="Project not found"/>;
 return <><Link className="back-link" to="/projects"><ArrowLeft size={15}/>All projects</Link><div className="project-heading"><div className="row gap"><ProjectIcon project={p}/><div><h1>{p.name}</h1><p>{p.description}</p></div></div><Status value={p.status}/></div><div className="project-subheader"><div className="row gap"><span className="env">Production</span>{p.url&&<External href={p.url}>{p.url.replace('https://','')}</External>}<span className="commit"><GitBranch size={14}/>{p.branch}</span></div><div className="row gap"><button className="button" onClick={()=>onDeploy(p,'rollback')}><RotateCcw size={15}/>Rollback</button><button className="button primary" onClick={()=>onDeploy(p)}><Rocket size={15}/>Deploy</button></div></div><div className="tabs">{['Overview','Builds','Deployments','Security','Health','Logs','Settings'].map(t=><button key={t} className={tab===t?'active':''} onClick={()=>setTab(t)}>{t}</button>)}</div>{tab==='Overview'&&<><Panel title="Latest deployment" action={latest&&<span className="muted">{ago(latest.started_at)}</span>}>{latest?<><div className="deployment-summary"><div><code>{latest.commit}</code><p>{latest.source} by {latest.actor}</p></div><Status value={latest.status}/></div><div className="pipeline">{['build','security','deploy','verification'].map((s,i)=><div key={s} className={latest.steps?.[s]||'pending'}><span>{latest.steps?.[s]==='passed'?<Check size={16}/>:i+1}</span><b>{s}</b><small>{latest.steps?.[s]||'pending'}</small></div>)}</div></>:<Empty title="Ready for a first release"/>}</Panel><div className="project-overview-grid"><Panel title={<><Activity size={18}/>Health checks</>}>{data.health_check.filter(c=>c.project===id).map(c=><div className="simple-row" key={c.id}><b>{c.name}</b><Status value={c.status}/><code>{c.latency} ms</code></div>)}</Panel><Panel title={<><ShieldCheck size={18}/>Security overview</>}>{['critical','high','medium','low'].map(s=><div className="simple-row" key={s}><Status value={s}/><b>{data.finding.filter(f=>f.project===id&&f.severity===s&&f.status==='open').length}</b></div>)}</Panel></div><Panel title="Deployment history"><DeploymentsTable deployments={deps} projects={data.project} onSelect={onSelect}/></Panel></>}{tab==='Deployments'&&<Panel><DeploymentsTable deployments={deps} projects={data.project} onSelect={onSelect}/></Panel>}{tab==='Builds'&&<Builds project={p} demo={data.demo}/ >}{tab==='Security'&&<Security data={data} project={id}/ >}{tab==='Health'&&<Health data={data} project={id}/ >}{tab==='Logs'&&<LogView deployments={deps}/ >}{tab==='Settings'&&<ProjectSettings project={p}/>}</>
}
function Builds({project,demo}:{project:Item;demo:boolean}){const q=useQuery({queryKey:['builds',project.id],queryFn:()=>api('/projects/'+project.id+'/builds')});return <Panel title="GitHub Actions" subtitle={demo?'Sample build history':'Workflow runs from the connected GitHub installation'}><ErrorNotice error={q.error}/>{q.isLoading?<p className="padding muted">Loading builds…</p>:q.data?.workflow_runs?.map((r:any)=><div className="simple-row" key={r.id}><div><b>{r.name||r.commit}</b><small>{r.head_branch||r.branch} · {r.actor?.login||r.actor}</small></div><Status value={r.conclusion||r.status}/>{r.html_url&&<External href={r.html_url}>View run</External>}</div>)}</Panel>}
function ProjectSettings({project:p}:{project:Item}){
 const action=useAction();const [name,setName]=useState(p.name);const [url,setUrl]=useState(p.url);const [publicStatus,setPublic]=useState(p.public);const [critical,setCritical]=useState(p.security_policy.block_critical);const [secretGate,setSecretGate]=useState(p.security_policy.block_secrets);const [cfg,setCfg]=useState(JSON.stringify(p.provider_config,null,2));const [saved,setSaved]=useState(false);const [error,setError]=useState<Error|null>(null);
 const [secretName,setSecretName]=useState('');const [secretValue,setSecretValue]=useState('');const [env,setEnv]=useState('production');const sq=useQuery({queryKey:['secrets',p.id],queryFn:()=>api<Item[]>(`/projects/${p.id}/secrets`)});
 return <div className="settings-grid"><Panel title="Project configuration"><form className="padding" onSubmit={async e=>{e.preventDefault();try{await action.mutateAsync({path:'/projects/'+p.id,method:'PATCH',body:{name,url,public:publicStatus,security_policy:{block_critical:critical,block_secrets:secretGate},provider_config:JSON.parse(cfg)}});setSaved(true);setError(null)}catch(e){setError(e as Error)}}}><label>Project name<input required value={name} onChange={e=>setName(e.target.value)}/></label><label>Production URL<input type="url" value={url} onChange={e=>setUrl(e.target.value)}/></label><label className="checkbox"><input type="checkbox" checked={publicStatus} onChange={e=>setPublic(e.target.checked)}/>Show sanitized status publicly</label><label className="checkbox"><input type="checkbox" checked={critical} onChange={e=>setCritical(e.target.checked)}/>Block critical vulnerabilities</label><label className="checkbox"><input type="checkbox" checked={secretGate} onChange={e=>setSecretGate(e.target.checked)}/>Block detected secrets</label><label>Provider configuration<textarea rows={6} value={cfg} onChange={e=>setCfg(e.target.value)}/></label><p className="help">{p.provider==='Vercel'?'Fields: project_id, repo_id, optional team_id.':p.provider==='GitHub Actions'?'Fields: installation_id, workflow (filename).':'Fields: agent_id, service (allowlisted Compose service).'}</p><ErrorNotice error={error}/><Submit pending={action.isPending}>{saved?'Saved':'Save configuration'}</Submit></form></Panel><Panel title={<><KeyRound size={18}/>Encrypted secrets</>} subtitle="Write once. Replace when needed. Never revealed."><form className="padding" onSubmit={async e=>{e.preventDefault();try{await action.mutateAsync({path:`/projects/${p.id}/secrets`,body:{name:secretName,value:secretValue,environment:env}});setSecretName('');setSecretValue('')}catch{}}}><label>Environment<select value={env} onChange={e=>setEnv(e.target.value)}>{p.environments.map((v:string)=><option key={v}>{v}</option>)}</select></label><label>Name<input required pattern="[A-Z][A-Z0-9_]*" value={secretName} onChange={e=>setSecretName(e.target.value)} placeholder="DATABASE_URL"/></label><label>Value<input required type="password" autoComplete="new-password" value={secretValue} onChange={e=>setSecretValue(e.target.value)} placeholder="Secret value"/></label><ErrorNotice error={action.error||sq.error}/><Submit pending={action.isPending}>Store secret</Submit></form>{sq.data?.map(s=><div className="simple-row" key={s.id}><div><b>{s.name}</b><small>{s.environment} · ••••••••</small></div><button className="icon-button" aria-label={'Delete secret '+s.name} onClick={()=>{if(window.confirm(`Delete ${s.name} from ${s.environment}?`))action.mutate({path:`/projects/${p.id}/secrets/${s.name}?environment=${s.environment}`,method:'DELETE'})}}><Trash2 size={16}/></button></div>)}</Panel></div>
}
